# MoAI-ADK Project Makefile
# Generated by moai init — customize as needed.

.PHONY: help ci-local pr-merge mcp-core-sync mcp-core-check mcp-core-test

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

ci-local: ## Run CI mirror locally (lint + vet + test + cross-compile)
	@./scripts/ci-mirror/run.sh

mcp-core-sync: ## Copy moai-mcp-core canonical source into every adopting MCP server
	@python3 scripts/sync-mcp-core.py

mcp-core-check: ## Fail if any vendored moai-mcp-core copy has drifted from canonical
	@python3 scripts/sync-mcp-core.py --check

mcp-core-test: ## Run the moai-mcp-core test suite
	@cd plugins/_shared/moai-mcp-core && uv run pytest -q

pr-merge: ## Enable GitHub auto-merge for a PR (Usage: make pr-merge PR=N [STRATEGY=squash|merge])
	@test -n "$(PR)" || (printf 'Usage: make pr-merge PR=<number> [STRATEGY=squash|merge]\n' >&2 && exit 1)
	@gh pr merge $(PR) --auto --$(or $(STRATEGY),squash)

.DEFAULT_GOAL := help
