#!/usr/bin/env bash
# skill-test-runner.sh — Execute skill test cases and report results
# Usage: ./scripts/skill-test-runner.sh <skill-dir> [--mode ab|regression|chain]
#
# Modes:
#   ab         — A/B test: baseline vs with-skill (default)
#   regression — Regression test: compare against last known results
#   chain      — Chain test: validate skill composition

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

MODE="ab"
SKILL_DIR=""

# Parse arguments
while [ $# -gt 0 ]; do
  case "$1" in
    --mode)
      MODE="$2"
      shift 2
      ;;
    *)
      SKILL_DIR="$1"
      shift
      ;;
  esac
done

if [ -z "$SKILL_DIR" ]; then
  echo "Usage: $0 <skill-dir> [--mode ab|regression|chain]"
  exit 1
fi

SKILL_FILE="$SKILL_DIR/SKILL.md"
TEST_FILE="$SKILL_DIR/tests/test-cases.yaml"

# Validate inputs
if [ ! -f "$SKILL_FILE" ]; then
  echo -e "${RED}ERROR${NC}: SKILL.md not found at $SKILL_FILE"
  exit 1
fi

# Extract skill name
SKILL_NAME=$(grep '^name:' "$SKILL_FILE" | head -1 | sed 's/^name: *//' | tr -d '"' | tr -d "'")

echo -e "${BLUE}=== Skill Test Runner ===${NC}"
echo "Skill: $SKILL_NAME"
echo "Mode: $MODE"
echo "Dir: $SKILL_DIR"
echo ""

# Check if test cases exist
if [ ! -f "$TEST_FILE" ]; then
  echo -e "${YELLOW}WARN${NC}: No test-cases.yaml found. Run skill-forge Phase 4 first."
  echo "Expected location: $TEST_FILE"
  echo ""
  echo "Creating template..."

  mkdir -p "$(dirname "$TEST_FILE")"
  cat > "$TEST_FILE" << YAML
skill: $SKILL_NAME
version: 1.0.0
test_cases:
  - id: TC-001
    name: "happy-path"
    prompt: |
      <대표적인 사용 프롬프트를 여기에 작성하세요>
    assertions:
      - type: contains
        value: "<출력에 포함되어야 할 문자열>"
      - type: format
        value: "markdown"
    quality_threshold:
      correctness: 0.75
      completeness: 0.70
      clarity: 0.70
      efficiency: 0.60

  - id: TC-002
    name: "edge-case"
    prompt: |
      <경계 조건 프롬프트를 여기에 작성하세요>
    assertions:
      - type: handles_gracefully
        value: true
YAML

  echo -e "${GREEN}Created${NC}: $TEST_FILE (template)"
  echo "Fill in the test prompts and re-run."
  exit 0
fi

# Count test cases
TC_COUNT=$(grep -c '^\s*- id:' "$TEST_FILE" 2>/dev/null || echo "0")
echo "Test cases found: $TC_COUNT"
echo ""

# Generate report header
REPORT_FILE="$SKILL_DIR/tests/report-$(date +%Y%m%d-%H%M%S).md"
mkdir -p "$(dirname "$REPORT_FILE")"

cat > "$REPORT_FILE" << HDR
## Skill Test Report: $SKILL_NAME

### Configuration
- Mode: $MODE
- Date: $(date +%Y-%m-%d)
- Test Cases: $TC_COUNT

### Instructions

This is a semi-automated test framework. To execute tests:

**For A/B Testing (Mode: ab):**
1. Run baseline (no skill): Copy each test prompt into Claude Code WITHOUT loading the skill
2. Run with-skill: Load the skill via \`/skill-name\` then run the same prompts
3. Compare outputs using the assertions in test-cases.yaml
4. Record scores below

**For Regression Testing (Mode: regression):**
1. Load the modified skill
2. Run all test cases
3. Compare against previous report in this directory
4. Flag any previously-passing assertions that now fail

**For Chain Testing (Mode: chain):**
1. Execute skills in documented chain order
2. Pass output of each step as input to next
3. Verify final output meets expectations

### Results

| TC ID | Name | Prompt | Assertions | Result | Notes |
|-------|------|--------|-----------|--------|-------|
HDR

# Add rows for each test case
grep '^\s*- id:' "$TEST_FILE" | while read -r line; do
  tc_id=$(echo "$line" | grep -oE 'TC-[0-9]+')
  tc_name=$(grep -A1 "$line" "$TEST_FILE" | grep 'name:' | sed 's/.*name: *//' | tr -d '"')
  echo "| $tc_id | $tc_name | - | - | PENDING | - |" >> "$REPORT_FILE"
done

cat >> "$REPORT_FILE" << FOOTER

### Scoring (fill in after execution)

| Dimension | Baseline | With-Skill | Delta |
|-----------|----------|------------|-------|
| Correctness | - | - | - |
| Completeness | - | - | - |
| Clarity | - | - | - |
| Efficiency | - | - | - |
| **Weighted** | **-** | **-** | **-** |

### Recommendation
_PENDING_

---
_Generated by skill-test-runner.sh_
FOOTER

echo -e "${GREEN}Report template created${NC}: $REPORT_FILE"
echo ""
echo "Next steps:"
echo "  1. Open $REPORT_FILE"
echo "  2. Execute test prompts in Claude Code"
echo "  3. Fill in results and scores"
echo "  4. Update recommendation (APPROVE / NEEDS REVISION)"
